name = "kuchbhi"
type = "javascript"
compatibility_date = "2025-07-04"

[build]
command = "npm run build"
upload.format = "modules"
upload.dir = "build"

[site]
bucket = "public"
entry-point = "."

[env.production]
vars = { NODE_ENV = "production" }
